### ISSUE TITLE
[Feature Request] adding @updateURL

### ISSUE THREAD

**Issue by black-backdoor** [AugmentedWeb/UserGui#7]
as far as i know imported scripts - @require are just the same as other userscripts so it should be possible to add @updateURL to your usergui.js file for automated updates

[https://stackoverflow.com/questions/72545851/how-to-make-userscript-auto-update-from-private-domain-github](https://stackoverflow.com/questions/72545851/how-to-make-userscript-auto-update-from-private-domain-github)

**Comment by Hakorr** [comment]
I'm sorry, but I don't know what you mean. There's no userscript header, this is a userscript library.
